version: 0.2

phases:
  install:
    commands:
        - mkdir install
        - cd install
        - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
        - unzip terraform_0.12.7_linux_amd64.zip
        - mv terraform /usr/bin/
        - cd ..
        - rm -rf install  
  
  build:
    commands:
        - cd terraform
        - terraform init -var="ACCESS_KEY=${ACCESS_KEY}" -var="SECRET_KEY=${SECRET_KEY}"
        - terraform apply -var="ACCESS_KEY=${ACCESS_KEY}" -var="SECRET_KEY=${SECRET_KEY}" -auto-approve
    
