version: 0.2

phases:
  install:
    commands:
        - mkdir install
        - cd install
        - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
        - unzip terraform_0.12.7_linux_amd64.zip
        - mv terraform /usr/bin/
        - cd ..
        - rm -rf install  
  build:
    commands:
        - cd terraform
        - sed -i 's/var_access/${ACCESS_KEY}/g' ./main.tf
        - sed -i 's/var_secret/${SECRET_KEY}/g' ./main.tf
        - cat ./main.tf
        - terraform init -upgrade
        - terraform apply -auto-approve
    
