version: 0.2

phases:
  install:
    commands:
        - wget https://releases.hashicorp.com/terraform/0.12.7/terraform_0.12.7_linux_amd64.zip
        - unzip terraform_0.12.7_linux_amd64.zip
        - sudo mv terraform /usr/local/bin/
        - sudo rm -rf terraform_0.12.7_linux_amd64.zip  
  
  build:
    commands:
        - cd terraform
        - terraform init
        - terraform apply -auto-approve
